# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: FlashCards Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "FlashCards Github Action was automatically triggered by a ${{ github.event_name }} event by ${{github.actor}}."
      - run: echo "The name of the branch is ${{ github.ref }}."
      - run: echo "The commit message is ${{github.event.head_commit.message}}."

      # Standardize commits and be able to find issues related to each ones
      # MIT License
      - name: Check commit message
        if: "!contains(github.event.head_commit.message, 'issue')"
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('The commit message has to provide the relater issue's number!')

      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Check for unnecessary imports
        run: dart analyze --fatal-infos --fatal-warnings --no-fatal-infos --no-fatal-warnings .

      # Tests
      - name: Run tests
        run: dart test

      - name: Done
        run: echo "All required steps have been checked."